### ISSUE TITLE
Finish implementing json serialisation

### ISSUE THREAD

**Issue by reedy** [pleonasm/bloom-filter#3]
It'd be nice if it worked... :)

https://github.com/pleonasm/bloom-filter/blob/master/src/Pleo/BloomFilter/BloomFilter.php#L113-L116

**Comment by pleonasm** [comment]
Very true! It's a bit awkward to serialize the data without having some indication of the amount (and type) of hash functions that were also used in the initial creation of the bloom filter.

But... on thinking of it a bit more I might have a solution. I know I haven't touched this in a while but I have some time this week and maybe I'll take a crack at it since someone is interested :) .

**Comment by pleonasm** [comment]
Closed by b8d98b0 .
